# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_auto_20160803_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='nr',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
