# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_bill_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bill',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, default=None),
            preserve_default=False,
        ),
    ]
