# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_auto_20160803_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='nip',
            field=models.CharField(default='', max_length=13, verbose_name='NIP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='city',
            field=models.CharField(max_length=200, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='zipcode',
            field=models.CharField(max_length=6, verbose_name='Kod pocztowy'),
        ),
    ]
