# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(max_length=25, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nazwa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='service',
            name='vat',
            field=models.FloatField(default=0, verbose_name='Stawka VAT'),
        ),
    ]
