# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-20 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20160803_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.CharField(default='', max_length=50, verbose_name='Jednostka'),
            preserve_default=False,
        ),
    ]
