# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_auto_20160803_1131'),
        ('contractor', '0004_auto_20160803_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('payed', models.BooleanField(default=False, verbose_name='Zap\u0142acono')),
                ('total', models.FloatField(default=0, verbose_name='W sumie')),
                ('due_date', models.DateField(verbose_name='Termin p\u0142atno\u015bci')),
                ('nr', models.CharField(max_length=20, verbose_name='Nr faktury')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contractor.Contractor', verbose_name='Nabywca')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceM2M',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Ilo\u015b\u0107')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('unit', models.CharField(max_length=50, verbose_name='Jednostka')),
                ('vat', models.FloatField(verbose_name='Stawka VAT')),
                ('discount', models.FloatField(verbose_name='Zni\u017cka')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceToInvoice',
            fields=[
                ('servicem2m_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoice.ServiceM2M')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice.Invoice')),
            ],
            bases=('invoice.servicem2m',),
        ),
        migrations.AddField(
            model_name='servicem2m',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='services',
            field=models.ManyToManyField(related_name='invoices', through='invoice.ServiceToInvoice', to='service.Service', verbose_name='Us\u0142ugi'),
        ),
    ]
