# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20160820_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicem2m',
            name='vat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
